version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: json-mapper/json-mapper
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: namelivia/travelperk-php-api-types
    versions:
    - 1.1.6
  - dependency-name: nesbot/carbon
    versions:
    - 2.45.0
    - 2.45.1
