version: '3'
services:

  travelperk-php-http-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travelperk-php-http-app
    entrypoint: "composer update"
    tty: false
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - vendor:/usr/src/app/vendor

volumes:
  vendor:
